const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function renderNav(){let path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')})}
renderNav();
let reminders=get('sm_reminders',[]), notes=get('sm_notes',[]), classes=get('sm_classes',[]);
function dateText(d){return new Date(d+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function status(d,done){if(done)return 'Completed';let t=new Date();t.setHours(0,0,0,0);let x=new Date(d+'T00:00:00');let n=Math.round((x-t)/86400000);return n<0?'Overdue':n===0?'Due today':n===1?'Tomorrow':'Due in '+n+' days'}
const form=document.getElementById('reminderForm');
if(form){document.getElementById('date').min=new Date().toISOString().split('T')[0];form.onsubmit=e=>{e.preventDefault();reminders.push({id:Date.now(),title:title.value.trim(),subject:subject.value.trim()||'General',date:date.value,priority:priority.value,completed:false});set('sm_reminders',reminders);form.reset();priority.value='medium';drawReminders()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawReminders(b.dataset.filter)});drawReminders()}
function drawReminders(filter='all'){const box=document.getElementById('reminderList');if(!box)return;let arr=reminders.filter(r=>filter==='all'||filter==='pending'&&!r.completed||filter==='completed'&&r.completed).sort((a,b)=>a.date.localeCompare(b.date));box.innerHTML=arr.length?arr.map(r=>`<article class="reminder ${r.priority} ${r.completed?'completed':''}"><input class="check" type="checkbox" ${r.completed?'checked':''} onchange="toggleReminder(${r.id})"><div><div class="rtitle">${esc(r.title)}</div><div class="meta">📘 ${esc(r.subject)} · 📅 ${dateText(r.date)} · ${status(r.date,r.completed)} · ${r.priority} priority</div></div><button class="delete" onclick="deleteReminder(${r.id})">🗑️</button></article>`).join(''):'<div class="card"><p>No reminders in this view.</p></div>'}
window.toggleReminder=id=>{let r=reminders.find(x=>x.id===id);r.completed=!r.completed;set('sm_reminders',reminders);drawReminders(document.querySelector('.filter.active')?.dataset.filter||'all')};window.deleteReminder=id=>{reminders=reminders.filter(x=>x.id!==id);set('sm_reminders',reminders);drawReminders(document.querySelector('.filter.active')?.dataset.filter||'all')};
if(document.getElementById('pending')){document.getElementById('pending').textContent=reminders.filter(x=>!x.completed).length;document.getElementById('done').textContent=reminders.filter(x=>x.completed).length;document.getElementById('notes').textContent=notes.length;document.getElementById('classes').textContent=classes.length;let u=document.getElementById('upcoming');let a=reminders.filter(x=>!x.completed).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);u.innerHTML=a.length?a.map(r=>`<div class="reminder ${r.priority}"><div>🔔</div><div><div class="rtitle">${esc(r.title)}</div><div class="meta">${esc(r.subject)} · ${dateText(r.date)} · ${status(r.date,false)}</div></div></div>`).join(''):'<p class="meta">No pending reminders. Great job! 🎉</p>'}
const cf=document.getElementById('classForm');if(cf){cf.onsubmit=e=>{e.preventDefault();classes.push({id:Date.now(),name:className.value.trim(),day:day.value,time:time.value,room:room.value.trim()});set('sm_classes',classes);cf.reset();drawClasses()};drawClasses()}
function drawClasses(){let box=document.getElementById('timetable');if(!box)return;let days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];box.innerHTML=days.map(d=>`<div class="day"><h4>${d}</h4>${classes.filter(c=>c.day===d).sort((a,b)=>a.time.localeCompare(b.time)).map(c=>`<div class="classitem"><button onclick="deleteClass(${c.id})">×</button><b>${esc(c.name)}</b>${c.time}${c.room?' · '+esc(c.room):''}</div>`).join('')||'<small class="meta">No classes</small>'}</div>`).join('')}
window.deleteClass=id=>{classes=classes.filter(x=>x.id!==id);set('sm_classes',classes);drawClasses()};
const nf=document.getElementById('noteForm');if(nf){nf.onsubmit=e=>{e.preventDefault();notes.unshift({id:Date.now(),title:noteTitle.value.trim(),text:noteText.value.trim()});set('sm_notes',notes);nf.reset();drawNotes()};drawNotes()}
function drawNotes(){let box=document.getElementById('notesList');if(!box)return;box.innerHTML=notes.length?notes.map(n=>`<article class="note"><button onclick="deleteNote(${n.id})">🗑️</button><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p></article>`).join(''):'<div class="card"><p>No notes saved yet.</p></div>'}
window.deleteNote=id=>{notes=notes.filter(x=>x.id!==id);set('sm_notes',notes);drawNotes()};
const pf=document.getElementById('profileForm');if(pf){let p=get('sm_profile',{});profileName.value=p.name||'';course.value=p.course||'';college.value=p.college||'';pf.onsubmit=e=>{e.preventDefault();set('sm_profile',{name:profileName.value,course:course.value,college:college.value});document.getElementById('profileMsg').textContent='Profile saved successfully ✓'}}
